// Especificaciones detalladas de los casos de uso arquitectónicamente significativos.
module.exports = [
  {
    id: 'CU-04', n: 'Consultar ficha técnica', actores: 'Visitante (principal)', estado: 'Parcial: existe; los datos no verificados aún no se marcan de forma sistemática',
    desc: 'El visitante revisa la información de un producto para evaluar si responde a su necesidad.',
    pre: ['El producto está en estado PUBLICADO.'],
    flujo: ['El visitante selecciona un producto desde el catálogo, la búsqueda, un destacado o un producto relacionado.', 'El sistema muestra el modelo, la categoría, la imagen principal y la galería.', 'El sistema muestra las especificaciones ordenadas por atributo.', 'El sistema muestra las acciones «Cotizar», «Comparar», «Copiar modelo» y «Compartir», y los productos relacionados.', 'El visitante revisa la información.'],
    alt: ['3a. Una especificación está en estado PENDIENTE: el sistema muestra «Pendiente de verificación» en lugar del valor (RN-03).', '3b. El producto no tiene especificaciones: el sistema muestra «Especificaciones en actualización» y mantiene la acción «Cotizar».', '5a. El visitante pulsa «Cotizar»: continúa en CU-08.', '5b. El visitante pulsa «Comparar»: continúa en CU-05.'],
    post: ['No se modifica ningún dato. No se muestra precio, carrito ni checkout (RN-01).'],
    reglas: 'RN-01, RN-03, RN-10', req: 'RF-004, RF-005, RF-006',
  },
  {
    id: 'CU-05', n: 'Comparar productos', actores: 'Visitante (principal)', estado: 'Existente en el rediseño; analítica anónima propuesta',
    desc: 'El visitante contrasta hasta tres modelos con las especificaciones alineadas por atributo.',
    pre: ['Hay al menos un producto publicado con especificaciones.'],
    flujo: ['El visitante pulsa «Comparar» en una tarjeta o ficha.', 'El sistema agrega el producto a la selección y actualiza el contador.', 'El visitante repite el paso 1 con otro producto.', 'El visitante abre el comparador.', 'El sistema solicita las especificaciones de los productos seleccionados y construye la tabla por atributo.', 'El sistema muestra una columna por producto con «Quitar» y «Cotizar por WhatsApp».'],
    alt: ['2a. La selección ya tiene 3 productos: el sistema rechaza el nuevo producto y muestra «Máximo 3 productos» (RN-04).', '2b. El producto ya está seleccionado: el sistema no lo duplica.', '5a. Un producto no tiene un atributo: la celda muestra «Pendiente de verificación».', '6a. El visitante pulsa «Quitar»: el sistema retira la columna y actualiza la selección.'],
    post: ['La selección se conserva al navegar entre páginas. Opcionalmente, se registra una ComparacionProducto anónima (propuesto).'],
    reglas: 'RN-03, RN-04', req: 'RF-007, RF-008, RF-009',
  },
  {
    id: 'CU-08', n: 'Enviar consulta por WhatsApp (incluye CU-09 Registrar consulta comercial)', actores: 'Cliente interesado (principal); Servicio externo de WhatsApp (secundario)', estado: 'Parcial: el enlace con el modelo existe; la URL en el mensaje y el registro son propuestos',
    desc: 'El cliente inicia una conversación comercial con el modelo y la intención ya escritos, y el sistema deja constancia de la consulta.',
    pre: ['El cliente está en una ficha, la vista rápida, el comparador, «Dónde comprar» o «Soporte».'],
    flujo: ['El cliente pulsa «Cotizar» (o «Contactar» en el directorio).', 'El sistema identifica el origen, la intención y, si corresponde, el producto.', 'El sistema construye el mensaje: saludo, intención, modelo y URL de la ficha.', 'El sistema registra la consulta en estado REGISTRADA mediante una llamada asíncrona (CU-09).', 'El sistema abre el enlace wa.me con el mensaje codificado.', 'El Servicio externo de WhatsApp abre el chat con el texto prellenado.', 'El cliente envía el mensaje.'],
    alt: ['2a. La consulta es general (home, footer): el mensaje no incluye modelo y la intención es COTIZAR sin producto.', '4a. El registro falla: el sistema no bloquea la apertura de WhatsApp y guarda el error en el log técnico.', '5a. El cliente eligió un distribuidor del directorio: el número de destino es el del distribuidor (propuesto).', '7a. El cliente cierra WhatsApp sin enviar: la consulta queda REGISTRADA y pasa a DESCARTADA a los 30 días sin atención.'],
    post: ['Existe un registro de ConsultaComercial sin datos personales. La conversación y la venta ocurren fuera del sistema.'],
    reglas: 'RN-01, RN-05, RN-07', req: 'RF-012, RF-013, RF-014',
  },
  {
    id: 'CU-12', n: 'Gestionar productos', actores: 'Gestor del catálogo (principal)', estado: 'Nativo de WooCommerce; validaciones y auditoría propuestas',
    desc: 'El gestor crea, edita, publica o descontinúa un producto del catálogo.',
    pre: ['El gestor inició sesión (CU-11) y tiene la capacidad edit_products.'],
    flujo: ['El gestor abre «Productos» y elige «Añadir» o un producto existente.', 'El gestor ingresa el modelo, el nombre, la descripción y las categorías.', 'El gestor carga las imágenes (CU-15) y las especificaciones (CU-14).', 'El gestor pulsa «Publicar».', 'El sistema valida el modelo único, al menos una categoría y la imagen principal con texto alternativo (RN-02).', 'El sistema cambia el estado a PUBLICADO y registra la auditoría (RN-09).', 'El sistema muestra la confirmación con un enlace a la ficha.'],
    alt: ['5a. Falta un dato obligatorio: el sistema indica el campo y conserva el estado BORRADOR.', '5b. El modelo ya existe: el sistema rechaza la operación (RN-10).', '4a. El gestor descontinúa el producto: el estado pasa a DESCONTINUADO, la ficha deja de listarse en el catálogo y la URL se conserva.'],
    post: ['Producto actualizado y registro de auditoría creado.'],
    reglas: 'RN-02, RN-09, RN-10', req: 'RF-017, RF-026',
  },
  {
    id: 'CU-16', n: 'Gestionar distribuidores', actores: 'Gestor del catálogo (principal)', estado: 'Propuesto (alcance académico)',
    desc: 'El gestor revisa las solicitudes de incorporación y mantiene el directorio de distribuidores.',
    pre: ['El gestor tiene la capacidad manage_distribuidores.'],
    flujo: ['El gestor abre «Distribuidores» y filtra por estado SOLICITADO.', 'El sistema lista las solicitudes con empresa, RUC, ciudad y fecha.', 'El gestor revisa una solicitud y verifica los datos.', 'El gestor pulsa «Aprobar».', 'El sistema cambia el estado a ACTIVO, registra la fecha de verificación y la auditoría.', 'El distribuidor aparece en el directorio público (RN-06).'],
    alt: ['4a. El gestor rechaza la solicitud: el estado pasa a RECHAZADO con un motivo.', '4b. Un distribuidor activo deja de operar: el gestor lo SUSPENDE y desaparece del directorio.', '3a. Faltan datos: el gestor contacta al solicitante y deja la solicitud en SOLICITADO.'],
    post: ['El directorio refleja solo a los distribuidores ACTIVOS.'],
    reglas: 'RN-06, RN-07, RN-09', req: 'RF-011, RF-021',
  },
  {
    id: 'CU-18', n: 'Dar seguimiento a consultas', actores: 'Gestor del catálogo (principal)', estado: 'Propuesto (alcance académico)',
    desc: 'El gestor actualiza el estado de las consultas para medir la atención y la derivación.',
    pre: ['Existen consultas registradas (CU-09).'],
    flujo: ['El gestor abre «Consultas» y filtra por estado y periodo.', 'El sistema lista las consultas con fecha, producto, origen, intención y estado.', 'El gestor selecciona una consulta REGISTRADA y pulsa «Atender».', 'El sistema cambia el estado a ATENDIDA y guarda el usuario y la hora.', 'El gestor asigna un distribuidor y pulsa «Derivar».', 'El sistema cambia el estado a DERIVADA.', 'Tras la confirmación, el gestor pulsa «Cerrar».'],
    alt: ['3a. La consulta es duplicada o no válida: el gestor la DESCARTA con un motivo.', '5a. La consulta se resuelve sin derivar: el gestor la cierra desde ATENDIDA.', '7a. El gestor intenta cerrar una consulta REGISTRADA: el sistema lo impide (RF-023).'],
    post: ['Estado actualizado y auditado; disponible para los reportes (CU-20).'],
    reglas: 'RN-09', req: 'RF-023, RF-025',
  },
];
