// Estado de cada requisito funcional en el sitio original (evidencia del 23-09 y 29-09-2026).
module.exports = {
  'RF-001': 'Recorrido mejorable: /shop/ vacía; las categorías sí listan',
  'RF-002': 'Existe: sugerencias en escritorio; en móvil no aparecieron',
  'RF-003': 'Parcial: orden y paginación, sin filtros',
  'RF-004': 'Existe: algunas fichas sin especificaciones',
  'RF-005': 'Inexistente',
  'RF-006': 'Existe: YITH Catalog Mode',
  'RF-007': 'Inexistente',
  'RF-008': 'Inexistente',
  'RF-009': 'Inexistente',
  'RF-010': 'Existe, sin contenido: el blog muestra «Nothing Found»',
  'RF-011': 'Inexistente',
  'RF-012': 'Poco visible: solo en «Ventas al mayor», sin mensaje',
  'RF-013': 'Inexistente',
  'RF-014': 'Inexistente',
  'RF-015': 'Poco visible: formulario en «Ventas al mayor», sin enlace en el menú',
  'RF-016': 'Existe (WordPress)',
  'RF-017': 'Existe (WooCommerce)',
  'RF-018': 'Existe (WooCommerce)',
  'RF-019': 'Existe como texto en la ficha',
  'RF-020': 'Recorrido mejorable: 34 imágenes de la home con texto alternativo vacío',
  'RF-021': 'Inexistente',
  'RF-022': 'Existe (WordPress)',
  'RF-023': 'Inexistente',
  'RF-024': 'Existe (WordPress)',
  'RF-025': 'Inexistente',
  'RF-026': 'Inexistente',
  'RF-027': 'Por verificar con el hosting',
};
